cabal-version:      3.4

name:               gauss-elimination
version:            0.3.0.0
synopsis:           Linear equation system solver using Gauss elimination algorithm
description:
  Coursework for "Functional Programming" course at Jagiellonian University.
  Solves linear equation systems using the Gauss elimination algorithm.
license:            MIT
license-file:       LICENSE
author:             Artem Shoobovych
maintainer:         shybovycha@gmail.com
category:           Math
build-type:         Simple

common warnings
  ghc-options:
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields

common language
  default-language: GHC2021

library
  import:           warnings, language
  hs-source-dirs:   src
  exposed-modules:
    EquationParser
    Fraction
    Gauss
    Matrix
    Map
    Parsing
    Set
  build-depends:    base ^>=4.18.0.0

executable gauss-elimination
  import:           warnings, language
  hs-source-dirs:   app
  main-is:          Main.hs
  build-depends:
    , base               ^>=4.18.0.0
    , gauss-elimination

test-suite doctests
  import:           warnings, language
  type:             exitcode-stdio-1.0
  hs-source-dirs:   test
  main-is:          Doctests.hs
  build-depends:
    , base     ^>=4.18.0.0
    , doctest  ^>=0.22
